### ISSUE TITLE
psycopg2.OperationalError SSL SYSCALL error: EOF detected

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#151]
An issue I recently run into. After starting the frontend with,
```
ramp-frontend launch --host 0.0.0.0
```
the home page works, but I get the following traceback when trying to access `/problems/` URL,
```
176.165.38.156 - - [24/Feb/2019 21:53:17] "GET /problems HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rth/src/ramp-board/ramp-frontend/ramp_frontend/views/ramp.py", line 82, in problems
    db.session, interaction='looking at problems', user=user
  File "/home/rth/src/ramp-board/ramp-database/ramp_database/tools/user.py", line 153, in add_user_interaction
    session.commit()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/rth/src/ramp-board/ramp-frontend/ramp_frontend/views/ramp.py", line 82, in problems
    db.session, interaction='looking at problems', user=user
  File "/home/rth/src/ramp-board/ramp-database/ramp_database/tools/user.py", line 153, in add_user_interaction
    session.commit()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1023, in commit
    self.transaction.commit()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 487, in commit
    self._prepare_impl()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 466, in _prepare_impl
    self.session.flush()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2436, in flush
    self._flush(objects)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2574, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2534, in _flush
    flush_context.execute()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 416, in execute
    rec.execute(self)   
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 583, in execute
    uow,
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1116, in _emit_insert_statements
    statement, params   
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 980, in execute
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
    distilled_params,   
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected
 [SQL: 'INSERT INTO user_interactions (timestamp, interaction, note, submission_file_diff, submission_file_similarity, ip, user_id, problem_id, event_team_id, submission_id, submission_file_id) VALUES (%(timestamp)s, %(interaction)s, %(note)s, %(submission_file_diff)s, %(submission_file_similarity)s, %(ip)s, %(user_id)s, %(problem_id)s, %(event_team_id)s, %(submission_id)s, %(submission_file_id)s) RETURNING user_interactions.id'] [parameters: {'timestamp': datetime.datetime(2019, 2, 24, 21, 53, 17, 62040), 'interaction': 'looking at problems', 'note': None, 'submission_file_diff': None, 'submission_file_similarity': None, 'ip': None, 'user_id': None, 'problem_id': None, 'event_team_id': None, 'submission_id': None, 'submission_file_id': None}] (Background on this error at: http://sqlalche.me/e/e3q8)
```
will investigate and report if I find the cause of it.

**Comment by rth** [comment]
Nevermind, that's just the message meaning that connection to the database couldn't be made (was an incorrect password in my case). It might still help to have a more explicit error message when that happens..

**Comment by rth** [comment]
No actually, it may be another issue than DB connection I think.

https://stackoverflow.com/q/24130305/1791279 seems to suggest it could be different causes. It happens on the second page when `add_user_interaction` is called (that why I thought it was initially solved).

I'm using Ubuntu 18.10 where postgres 10.6. Is there any other information that it would be useful to provide in order to debug this?

FWIW, after I create the `databoard_test` database as done in Travis CI, all tests in `ramp-database` pass (except for the `test_update_leaderboard_functions` that fails because of the missing `ramp-iris` conda env which shouldn't be relevant). So overall the database package and connection  appears to be working as expected.

Tried to re-create the database with,
```
sudo -u postgres createdb --owner=rampadmin ramp_db2
ramp-utils deploy-ramp-event --force
```
and updated the database name in `config.yml` but I still get the same error as above..

**Comment by rth** [comment]
For the record, in the logs I was seeing,
```
2019-03-04 22:11:20.666 UTC [2171] rampadmin@ramp_db2 LOG:  SSL error: decryption failed or bad record mac
2019-03-04 22:11:20.666 UTC [2171] rampadmin@ramp_db2 LOG:  could not receive data from client: Connection reset by peer
```

and editing
```
/etc/postgresql/10/main/postgresql.conf
```
to comment out all lines with SSL, seems to have solved this issue.

**Comment by jorisvandenbossche** [comment]
Do you also *understand* why it is solved? (or what the original problem was)

**Comment by rth** [comment]
I imagine something wrong with the default SSL config for postgres on Ubuntu 18.10 in my case. Maybe the SSL certificates I had were invalid (I have not done anything special -- just installed postres via `apt-get`). Anyway for local connection SSL shouldn't matter..

**Comment by rth** [comment]
Also, it was a server with a newly installed Ubuntu 18.10 so there shouldn't have been any special environment settings.

**Comment by jorisvandenbossche** [comment]
OK, so I have the same problem locally with my system postgresql, while with one installed by conda it was working fine. Due to different defaults for ssl (disabled on the conda one), and after commenting out as you mentioned it also works for the system postgres.

There were several people this morning that had the same problem. 
Is the only solution to actually disable ssl in postgres? I assume we can fix something in our code that you don't need to disable the ssl?

**Comment by rth** [comment]
> while with one installed by conda it was working fine

Aww I didn't know that postgres was packaged in conda..

> Is the only solution to actually disable ssl in postgres?

I guess postgres should work with default settings, there must be some fix I would think. Also it's interesting to analyze why unit tests still worked in that case (for me at least).

**Comment by jorisvandenbossche** [comment]
So with `app.run(..., processes=1)` it works with ssl enabled as well. (before we had there `processes=1000` in the code)

**Comment by jorisvandenbossche** [comment]
So I did a PR to set it to 1 for the test-launch command, which should hopefully fix such problems when testing it out. Of course, if you do an actual deployment, you probably need to use something that scales better.

**Comment by rth** [comment]
> (before we had there processes=1000 in the code)

Hah, yes that certainly looks like the issue. In general it would have been good to run NGNIX or something in front of flask, though not sure how to do that without requiring lots of extra configuration.
