### ISSUE TITLE
FileNotFoundError when executing submissions

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#154]
I am working on the solar wind problem, and to test I submitted the starting kit the few times.

The first one was run fine. The second (and the following ones) errored with the following traceback, 

```
Traceback (most recent call last):
  File "/home/rth/miniconda3/envs/ramp-solar-wind/lib/python3.7/site-packages/rampwf/utils/submission.py", line 96, in train_test_submission
    module_path, X_train, y_train, train_is=train_is)
  File "/home/rth/ramp-deployment/ramp-kits/solar_wind/problem.py", line 43, in train_submission
    module_path, X_df, y_array, train_is)
  File "/home/rth/miniconda3/envs/ramp-solar-wind/lib/python3.7/site-packages/rampwf/workflows/feature_extractor.py", line 11, in train_submission
    feature_extractor = import_file(module_path, self.element_names[0])
  File "/home/rth/miniconda3/envs/ramp-solar-wind/lib/python3.7/site-packages/rampwf/utils/importing.py", line 32, in import_file
    submitted_module = imp.load_source(submitted_path, submitted_file)
  File "/home/rth/miniconda3/envs/ramp-solar-wind/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "/home/rth/miniconda3/envs/ramp-solar-wind/lib/python3.7/imp.py", line 157, in get_data
    return super().get_data(path)
  File "<frozen importlib._bootstrap_external>", line 916, in get_data

FileNotFoundError: [Errno 2] No such file or directory: '/home/rth/ramp-deployment/submissions/submission_000000004/feature_extractor.py'
```

which is strange because of that `feature_extractor.py` at that path exists and looks fine. Restarting the dispatcher at the time didn't help.

Today I have restarted both the frontend and the dispatcher again and the job appears to be running, the dispatcher shows,
```
2019:03:05 07:10:27 - INFO - RAMP-DISPATCHER - Worker CondaEnvWorker(submission_000000006): status="running" is still running
```
but in the log I already have the same error for the newly created job..

Have anyone encountered this before? I can provide access to the server if it helps investigating..

**Comment by rth** [comment]
> I have restarted both the frontend and the dispatcher again and the job appears to be running, the dispatcher shows,[...] but in the log I already have the same error for the newly created job..

No actually the job is running fine I think -- it just hasn't created log files so I was looking at the previous ones.

Though why this issue happened in the first place is still an open question..

**Comment by rth** [comment]
I think the previous time it worked because the worker was still running, I restarted it, and that it successfully run the pending job.

When a job is submitted with an available worker I systematically get the above error. 

The server log at that time looks like,
```
37.171.220.xx - - [05/Mar/2019 08:08:44] "POST /events/solar_wind_test/sandbox HTTP/1.1" 302 -
37.171.220.xx - - [05/Mar/2019 08:08:45] "GET /credit/b7ced64b946c4b57f7427b4b4cf882ba1702763d HTTP/1.1" 200 -
37.171.220.xx - - [05/Mar/2019 08:08:51] "POST /credit/b7ced64b946c4b57f7427b4b4cf882ba1702763d HTTP/1.1" 302 -
37.171.220.xx - - [05/Mar/2019 08:08:52] "GET /events/solar_wind_test/sandbox HTTP/1.1" 200 -
```
and the dispatcher was started with,
```
ramp-launch dispatcher --hunger-policy sleep --verbose --event-config config.yml
```

**Comment by rth** [comment]
Upon further investigation, in my case when the exception happens in 
`ramp-workflow/rampwf/utils/importing.py` while calling `imp.load_source(submitted_path, submitted_file)`,

the variables are, `submitted_path=homerthramp-deploymentsubmissions.submission_000000015.feature_extractor, submitted_file=/home/rth/ramp-deployment/submissions/submission_000000015/feature_extractor.py`. The `submission_000000015` folder does exist, but it then contains `training_output` file. When I look at that same folder after the run was killed it does contain the `classifier.py         feature_extractor.py` files as expected.

A few notes:
 - I guess the dash the `submitted_path` might be an issue?
 - Could there be some synchronization issue (i.e. trying to access that file before it is created)?

**Comment by rth** [comment]
FWIW, I re-created the database and re-deployed the event with `deployment_dir` that doesn't include a dash -- that didn't help for this errors.

I don't know if you saw anything relevant on the server @jorisvandenbossche ? 

Sounds like a synchronization issue with the dispatcher.

**Comment by rth** [comment]
@glemaitre You wouldn't have an idea why this could be happening (or where to look)? Currently this means I have to manually restart each new submission (i.e. work as a human dispatcher) ^^

**Comment by rth** [comment]
@glemaitre I can confirm your hotfix is working! I'm really enthusiastic about it!
