### ISSUE TITLE
NameClashError: username is already in use as a team name and email is already in use

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#155]
When creating test users I must have entered some field as duplicates, and got the following exception,
```
"POST /sign_up HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rth/src/ramp-board/ramp-frontend/ramp_frontend/views/auth.py", line 135, in sign_up
    access_level='asked'
  File "/home/rth/src/ramp-board/ramp-database/ramp_database/tools/user.py", line 108, in add_user
    raise NameClashError(message)
ramp_database.exceptions.NameClashError: username is already in use as a team name and email is already in use
```

At least a duplicate email is detected in form validation I think? I'm not sure why this one got through validation (I can't remember what was the input exactly).

Not too critical just FYI.

**Comment by glemaitre** [comment]
You cannot add a user with the same username or email. We raise an error in this case.
Would you expect something different?

**Comment by rth** [comment]
I would expect the form to display a validation error if the username or email already exists (and in does so in some cases), not the whole frontend to crash with a traceback in that case..

**Comment by glemaitre** [comment]
Oh this is in a form. Right, it should be validated. I was thinking that it was a command line.
