### ISSUE TITLE
Re-running failed submission with ramp-launch worker

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#165]
I am trying to manually re-run a submission failed due to #154  using,
```
ramp-launch worker --submission <submission_name>
```

and I run into two other issues,
 - [x] the submission name doesn't seem to be validated against the list of exiting submissions. For instance,
  ```
  ramp-launch worker --submission anything --verbose
  ```
  will create a  `submissions/anything` folder then unsurprisingly fail due to,
  ```
  FileNotFoundError: [Errno 2] No such file or directory: '/home/rth/ramp_deployment2/submissions/anything/feature_extractor.py'
  ```
  Not too critical but it might be better to fails with some explicit error message on the CLI.

 - [ ] When using a correct submission name, for a submission that previously failed, I get,
  ```
  ramp-launch worker --submission submission_000000006/ --verbose
2019:03:06 20:12:05 - INFO - RAMP-WORKER - CondaEnvWorker(submission_000000006/): status="setup"
2019:03:06 20:12:05 - INFO - RAMP-WORKER - CondaEnvWorker(submission_000000006/): status="running"


Traceback (most recent call last):
  File "/home/rth/miniconda3/envs/ramp-board/bin/ramp-launch", line 11, in <module>
    load_entry_point('ramp-engine', 'console_scripts', 'ramp-launch')()
  File "/home/rth/src/ramp-board/ramp-engine/ramp_engine/cli.py", line 87, in start
    main()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/rth/src/ramp-board/ramp-engine/ramp_engine/cli.py", line 83, in worker
    worker.launch()
  File "/home/rth/src/ramp-board/ramp-engine/ramp_engine/base.py", line 91, in launch
    self.collect_results()
  File "/home/rth/src/ramp-board/ramp-engine/ramp_engine/local.py", line 166, in collect_results
    shutil.copytree(output_training_dir, pred_dir)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/shutil.py", line 321, in copytree
    os.makedirs(dst)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
    File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/rth/ramp_deployment2/preds/submission_000000006/'
   ```

probably a `--force` option to overwrite exising dirs would be useful.

**Comment by glemaitre** [comment]
I think the easiest is to change manually the status of the submission in the database such that the dispatcher take it back on the next loop:

```
ramp-database set-submission-state --submission-id 6 --state new
```

**Comment by glemaitre** [comment]
We should probably document when you are in this is situation.

**Comment by rth** [comment]
> I think the easiest is to change manually the status of the submission in the database such that the dispatcher take it back on the next loop:

Thanks for the suggestion! That should work, though because I potentially have issues with the dispatcher in https://github.com/paris-saclay-cds/ramp-board/issues/154 I would rather also have an option to run a submission with as little abstraction as possible.

Tried to address it in https://github.com/paris-saclay-cds/ramp-board/pull/167 -- will see if runs fine.
