### ISSUE TITLE
psycopg2.DatabaseError: error with status PGRES_TUPLES_OK and no message from the libpq

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#178]
An issue on the frontend that keeps happening now that my RAMP instance sees some traffic. Once it happens once, it applies to all pages that need a database connection.  

Restarting postgres doesn't help. The only solution is to restart the frontend. It starts happening every couple of hours in my case.

```
"GET /problems HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rth/src/ramp-board/ramp-frontend/ramp_frontend/views/ramp.py", line 82, in problems
    db.session, interaction='looking at problems', user=user
  File "/home/rth/src/ramp-board/ramp-database/ramp_database/tools/user.py", line 153, in add_user_interaction
    session.commit()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1023, in commit
    self.transaction.commit()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 491, in commit
    t[1].commit()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1708, in commit
    self._do_commit()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1739, in _do_commit
    self.connection._commit_impl()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 755, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception  
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 753, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 489, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.DatabaseError: (psycopg2.DatabaseError) error with status PGRES_TUPLES_OK and no message from the libpq (Background on this error at: http://sqlalche.me/e/4xp6)
```

Very likely related to https://github.com/psycopg/psycopg2/issues/281

Running the app with `process=4`, that might be related.

## Versions

postgres: 10+193 (from system ubuntu 18.10)
psycopg2: 2.7.6.1          py37h1ba5d50_0 (conda)
libpq-dev: 10.5-1 (from system ubuntu 18.10)

**Comment by rth** [comment]
From https://github.com/psycopg/psycopg2/issues/281#issuecomment-264860868,

> you know that you cannot use a connection in a separate process, right? You should create instead a new connection in the working process.

@glemaitre Do you know if we are always creating a new connection when spawning a process (instead of reusing an existing one)? I feel like this could be the root cause..

**Comment by glemaitre** [comment]
Yes but I have the impression that this is not us but flask sqlalchemy which does that. I am creating a single engine and use it across the views of the frontend. Somehow something is forking it most probably. 
                                                                                                                                      
 

                            
     

Sent from my phone - sorry to be brief and potential misspell.

**Comment by rth** [comment]
Switched to using gunicorn instead of the built-in flask server, and so far I am not seeing this issue. It is very likely that `processes > 1` in flask was the culprit.

Closing, will re-open if it happens again.
