### ISSUE TITLE
select_submission_by_name: sqlalchemy.orm.exc.NoResultFound: No row was found for one

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#181]
Another exception I saw in the frontend logs,

```
Submission starting_k already exists. Please change the name.
You need to wait 819 more seconds until next submission
[2019-03-07 22:53:47 +0000] [17904] [ERROR] Error handling request /64bece7bf958d9621b4e29a475759dfc68f85374/feature_extractor.py
Traceback (most recent call last):
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/rth/src/ramp-board/ramp-frontend/ramp_frontend/views/ramp.py", line 710, in view_model
    submission.name)):
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/rth/src/ramp-board/ramp-frontend/ramp_frontend/views/ramp.py", line 710, in view_model
    submission.name)):
  File "/home/rth/src/ramp-board/ramp-database/ramp_database/tools/frontend.py", line 113, in is_accessible_code
    submission_name)
  File "/home/rth/src/ramp-board/ramp-database/ramp_database/tools/_query.py", line 95, in select_submission_by_name
    .order_by(Submission.submission_timestamp)
  File "/home/rth/miniconda3/envs/ramp-board/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3046, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
feature_extractor5.py is not in the file list.
Submission name should have length between 4 and 20 characters.
Error: 'ascii' codec can't encode character '\xe7' in position 0: ordinal not in range(128)
```
I think the user may have tried to update an existing submission but not sure. I'll need to investigate.

**Comment by rth** [comment]
Can confirm this is still happening with the current master and a different problem setup. It's probably not too critical..
