### ISSUE TITLE
FileNotFoundError ramp-frontend/ramp_frontend/static/img/powered_by/

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#300]
After including https://github.com/paris-saclay-cds/ramp-board/pull/286 the frontend produces the following exception for the home page for me. 

```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/testenv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app                        
    response = self.full_dispatch_request()
  File "/home/ubuntu/miniconda3/envs/testenv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request           
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/miniconda3/envs/testenv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception           
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/miniconda3/envs/testenv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise                       
    raise value
  File "/home/ubuntu/miniconda3/envs/testenv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request           
    rv = self.dispatch_request()
  File "/home/ubuntu/miniconda3/envs/testenv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request                
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/src/ramp-board/ramp-frontend/ramp_frontend/views/general.py", line 17, in index                                  
    'ramp-frontend/ramp_frontend/static/img/powered_by/')
FileNotFoundError: [Errno 2] No such file or directory: 'ramp-frontend/ramp_frontend/static/img/powered_by/'                          
```
Since the path should be provided with respect to where the package is installed, not the folder from which the frontend was started.

cc @maikia

**Comment by akazakci** [comment]
Hello,
Had the same issue during deployment to AWS; fixed it by removing that part of the code from under Anaconda.
Surely there was some more elegant way to do?
