### ISSUE TITLE
BUG pip install git+ error

### ISSUE THREAD

**Issue by lucyleeow** [paris-saclay-cds/ramp-board#417]
Running `pip install git+git://github.com/paris-saclay-cds/ramp-board.git` gives:
```
Collecting git+git://github.com/paris-saclay-cds/ramp-board.git
  Cloning git://github.com/paris-saclay-cds/ramp-board.git to /tmp/pip-req-build-et1g1o3o
  Running command git clone -q git://github.com/paris-saclay-cds/ramp-board.git /tmp/pip-req-build-et1g1o3o
    ERROR: Command errored out with exit status 1:
     command: /home/lucy/miniconda3/envs/test/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-et1g1o3o/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-et1g1o3o/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-et1g1o3o/pip-egg-info
         cwd: /tmp/pip-req-build-et1g1o3o/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/lucy/miniconda3/envs/test/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-et1g1o3o/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

@glemaitre mentioned it might be a pip issue?

**Comment by rth** [comment]
Shouln't it be `pip install git+ssh://` or `git+https://` ?

**Comment by lucyleeow** [comment]
Huh I've found all 3 types but not good explanation. Do you have a reference?

**Comment by lucyleeow** [comment]
That explains the difference?

**Comment by lucyleeow** [comment]
`pip install git+https://github.com/paris-saclay-cds/ramp-board.git` gives same error

**Comment by rth** [comment]
I have always used `git+ssh` TBH, but you are right the other one is also possible https://pip.pypa.io/en/stable/reference/pip_install/#git

The underlying issue is that ramp-board is not a 1 python package, but 3 each in their subfolders. And someone one has to run https://github.com/paris-saclay-cds/ramp-board/blob/133fb24c9b23bf9908933d4d217428ae826fedce/Makefile#L12-L15. Given how few people would install it themselves, I'm not sure if making `pip install ramp-board` work is really worth it..

**Comment by lucyleeow** [comment]
I agree - I was just trying to get the latest version as the latest release on PyPI did not have a required feature. Is there a way to install from github the individual packages?

**Comment by lucyleeow** [comment]
Also what is difference between `git+git`, `git+https` etc? The way that the data is downloaded...??

**Comment by agramfort** [comment]
git+ssh requires you to have git installed.

I always recommend something like

pip install -U https://api.github.com/repos/mne-tools/mne-python/zipball/master

**Comment by rth** [comment]
> I always recommend something like
> pip install -U https://api.github.com/repos/mne-tools/mne-python/zipball/master

+1 . I meant that if you actually want to use ssh and git, `git+ssh` it is. But yeah, in most cases directly pointing to the archive is simpler.

**Comment by lucyleeow** [comment]
I'm not familiar with this and the internet wasn't clear. Can you just use `pip install https://github.com/paris-saclay-cds/ramp-board/zipball/master` or do you need to do something to create the zipball?

Regardless the above command gave this error:
```
Traceback (most recent call last):
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 755, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 699, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 70, in _safe_read
    data = self.__fp._safe_read(amt)
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/http/client.py", line 610, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(5422 bytes read, 4818 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    local_path = unpack_url(
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 282, in unpack_url
    return unpack_http_url(
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 158, in unpack_http_url
    from_path, content_type = _download_http_url(
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 303, in _download_http_url
    for chunk in download.chunks:
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/utils/ui.py", line 160, in iter
    for x in it:
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 15, in response_chunks
    for chunk in response.raw.stream(
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 560, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 781, in read_chunked
    self._original_response.close()
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/lucy/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(5422 bytes read, 4818 more expected)', IncompleteRead(5422 bytes read, 4818 more expected))
```

**Comment by rth** [comment]
> Can you just use pip install https://github.com/paris-saclay-cds/ramp-board/zipball/master or do you need to do something to create the zipball?

For that to work you need a `setup.py` in the root folder, which is not the case `ramp-board`. So it's normal that it doesn't work. There are likely some workarounds, but I'm not sure that's an issue that's worth solving TBH. In particular, this package won't work as long as the database is not started anyway, and would not recommend doing any database related actions at install..

**Comment by lucyleeow** [comment]
Ah

> For that to work you need a `setup.py` in the root folder, which is not the case `ramp-board`. So it's normal that it doesn't work.

Ah makes sense. Agreed that it is more effort than its worth. @glemaitre suggested that we pip install the package on the server instead of downloading and installing locally, so we need to make a new release to use a new feature. Of course we can always just download and install. I'll close this.
