### ISSUE TITLE
BUG error when training on AWS instances

### ISSUE THREAD

**Issue by maikia** [paris-saclay-cds/ramp-board#479]
New type of error was spotted when training on the AWS instances.
This led to the breaking of the dispatcher

```
2020-11-26 12:05:45,729 RAMP-AWS ERROR Unhandled exception occurred when checking for instance action: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/miniconda3/bin/ramp-launch", line 8, in <module>
    sys.exit(start())
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/cli.py", line 122, in start
    main()
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/cli.py", line 90, in dispatcher
    disp.launch()
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/dispatcher.py", line 296, in launch
    self.collect_result(session)
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/dispatcher.py", line 206, in collect_result
    elif worker.status == 'running':
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/base.py", line 82, in status
    elif self._is_submission_finished():
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/aws/worker.py", line 116, in _is_submission_finished
    self.config, self.instance.id, self.submission)
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/aws/api.py", line 767, in _training_finished
    return not _has_screen(config, instance_id, submission_name)
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/aws/api.py", line 810, in _has_screen
    nb = int(_run(config, instance_id, cmd, return_output=True))
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/aws/api.py", line 736, in _run
    ip = inst.public_ip_address
  File "/opt/miniconda3/lib/python3.7/site-packages/boto3/resources/factory.py", line 345, in property_loader
    return self.meta.data.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by lucyleeow** [comment]
Not sure how helpful this is but the boto3 code for the last call is [here](https://boto3.amazonaws.com/v1/documentation/api/latest/_modules/boto3/resources/factory.html):
```Python
    def _create_autoload_property(factory_self, resource_name, name,
                                  snake_cased, member_model, service_context):
        """
        Creates a new property on the resource to lazy-load its value
        via the resource's ``load`` method (if it exists).
        """
        # The property loader will check to see if this resource has already
        # been loaded and return the cached value if possible. If not, then
        # it first checks to see if it CAN be loaded (raise if not), then
        # calls the load before returning the value.
        def property_loader(self):
            if self.meta.data is None:
                if hasattr(self, 'load'):
                    self.load()
                else:
                    raise ResourceLoadException(
                        '{0} has no load method'.format(
                            self.__class__.__name__))

            return self.meta.data.get(name)
```
so it seems that maybe this is a problem with the instance, which cannot be 'loaded'.
