### ISSUE TITLE
BUG dispatcher failing on lack of instance

### ISSUE THREAD

**Issue by maikia** [paris-saclay-cds/ramp-board#492]
Another error related to AWS.

```
Traceback (most recent call last):
  File "/opt/miniconda3/bin/ramp-launch", line 8, in <module>
    sys.exit(start())
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/cli.py", line 122, in start
    main()
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/cli.py", line 90, in dispatcher
    disp.launch()
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/dispatcher.py", line 309, in launch
    self.launch_workers(session)
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/dispatcher.py", line 171, in launch_workers
    worker.teardown()  # kill the worker
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/aws/worker.py", line 190, in teardown
    self.config, self.instance.id
AttributeError: 'AWSWorker' object has no attribute 'instance'
```

**Comment by tomMoral** [comment]
I saw the same error today. Is there an easy fix?

**Comment by maikia** [comment]
Yes. very easy. but we need another release. This #494 will take care of it
