### ISSUE TITLE
CalledProcessError on AWS

### ISSUE THREAD

**Issue by maikia** [paris-saclay-cds/ramp-board#496]
Yet another error came up on the worker running on AWS:
```
2020:12:16 00:28:35 - DEBUG - RAMP-AWS - ssh -o 'StrictHostKeyChecking no' -i /home/ramp/.ssh/aws_ramp_ireland.pem ubuntu@3.249.175.121 "screen -ls|awk '{print $1}' | cut -d. -f2 | grep submission_000006581| wc
-l"
Connection closed by 3.249.175.121 port 22
Traceback (most recent call last):
  File "/opt/miniconda3/bin/ramp-launch", line 8, in <module>
    sys.exit(start())
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/cli.py", line 122, in start
    main()
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/cli.py", line 90, in dispatcher
    disp.launch()
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/dispatcher.py", line 310, in launch
    self.collect_result(session)
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/dispatcher.py", line 220, in collect_result
    elif worker.status == 'running':
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/base.py", line 82, in status
    elif self._is_submission_finished():
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/aws/worker.py", line 130, in _is_submission_finished
    self.config, self.instance.id, self.submission)
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/aws/api.py", line 797, in _training_finished
    return not _has_screen(config, instance_id, submission_name)
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/aws/api.py", line 840, in _has_screen
    nb = int(_run(config, instance_id, cmd, return_output=True))
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/aws/api.py", line 776, in _run
    return subprocess.check_output(cmd, shell=True)
  File "/opt/miniconda3/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/opt/miniconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'ssh -o 'StrictHostKeyChecking no' -i /home/ramp/.ssh/aws_ramp_ireland.pem ubuntu@3.249.175.121 "screen -ls|awk '{print $1}' | cut -d. -f2 | grep submission_000006581| wc -l"' returned non-zero exit status 255.
```

**Comment by lucyleeow** [comment]
This looks like the same as in #487 ? But supposedly it was fixed?

**Comment by maikia** [comment]
Hopefully this one is fixed
