### ISSUE TITLE
Internal error for the plot score vs. time

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-board#577]
I get an error when trying to show the score vs. time:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/7454015/169646175-e8ec72cd-f346-4943-80fe-ce1d4a1013ab.png">

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/7454015/169646189-78d2de7a-c5d9-4411-ab79-537ee7881bdf.png">

We should have some python code failing somewhere.

**Comment by glemaitre** [comment]
FYI, the log error:

```pytb
May 21 09:56:14 ramp.studio gunicorn[28387]: [2022-05-21 09:56:14,889] [ERROR] Exception on /event_plots/air_passengers_dssp_21 [GET]
May 21 09:56:14 ramp.studio gunicorn[28387]: Traceback (most recent call last):
May 21 09:56:14 ramp.studio gunicorn[28387]:   File "/opt/miniconda3/envs/new-server/lib/python3.8/site-packages/flask/app.py", line 2073, in
May 21 09:56:14 ramp.studio gunicorn[28387]:     response = self.full_dispatch_request()
May 21 09:56:14 ramp.studio gunicorn[28387]:   File "/opt/miniconda3/envs/new-server/lib/python3.8/site-packages/flask/app.py", line 1518, in
May 21 09:56:14 ramp.studio gunicorn[28387]:     rv = self.handle_user_exception(e)
May 21 09:56:14 ramp.studio gunicorn[28387]:   File "/opt/miniconda3/envs/new-server/lib/python3.8/site-packages/flask/app.py", line 1516, in
May 21 09:56:14 ramp.studio gunicorn[28387]:     rv = self.dispatch_request()
May 21 09:56:14 ramp.studio gunicorn[28387]:   File "/opt/miniconda3/envs/new-server/lib/python3.8/site-packages/flask/app.py", line 1502, in
May 21 09:56:14 ramp.studio gunicorn[28387]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
May 21 09:56:14 ramp.studio gunicorn[28387]:   File "/opt/miniconda3/envs/new-server/lib/python3.8/site-packages/flask_login/utils.py", line 
May 21 09:56:14 ramp.studio gunicorn[28387]:     return func(*args, **kwargs)
May 21 09:56:14 ramp.studio gunicorn[28387]:   File "/opt/miniconda3/envs/new-server/lib/python3.8/site-packages/ramp_frontend/views/ramp.py"
May 21 09:56:14 ramp.studio gunicorn[28387]:     p = score_plot(db.session, event)
May 21 09:56:14 ramp.studio gunicorn[28387]:   File "/opt/miniconda3/envs/new-server/lib/python3.8/site-packages/ramp_frontend/views/visualiz
May 21 09:56:14 ramp.studio gunicorn[28387]:     fill_colors_1 = color_gradient(
May 21 09:56:14 ramp.studio gunicorn[28387]:   File "/opt/miniconda3/envs/new-server/lib/python3.8/site-packages/ramp_frontend/views/visualiz
May 21 09:56:14 ramp.studio gunicorn[28387]:     colors = gray2rgb(
May 21 09:56:14 ramp.studio gunicorn[28387]: IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
```

**Comment by glemaitre** [comment]
I should probably stop to click everywhere today :)

**Comment by rth** [comment]
As far as I can tell, there is one extra slicing depth in https://github.com/paris-saclay-cds/ramp-board/blob/fdcbe4fed4b8da71225f5fc45aba059bfea1ae4b/ramp-frontend/ramp_frontend/views/visualization.py#L46 which needs removing.

Minimal example to reproduce,
```py
from ramp_frontend.views.visualization import color_gradient

fill_color_1 = (176, 23, 31)

color_gradient(fill_color_1, [0.5, 0.1, 0.3])
```

That code was last changed 5 years ago, and I can't see anything relevant in scikit-image changelog, so no idea why this is happening :)

**Comment by frcaud** [comment]
@rth  @glemaitre  Test on a local server on my machine gives me this warning that can be related to what we observe:
```ramp-frontend/ramp_frontend/views/visualization.py:43: FutureWarning: The behavior of rgb2gray will change in scikit-image 0.19. Currently, rgb2gray allows 2D grayscale image to be passed as inputs and leaves them unmodified as outputs. Starting from version 0.19, 2D arrays will be treated as 1D images with 3 channels.```
