### ISSUE TITLE
password checking failing with local test

### ISSUE THREAD

**Issue by jorisvandenbossche** [paris-saclay-cds/ramp-board#79]
Serving locally, and added a user with invoke, and then trying to login gives me:

```
INFO: 127.0.0.1 - - [28/Nov/2018 17:15:31] "POST /login?next=%2Fevents%2Fnew_test HTTP/1.1" 500 -
ERROR: Error on request:
Traceback (most recent call last):
  File "/media/joris/DATA/CDS/RAMP/conda-env-ramp/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/media/joris/DATA/CDS/RAMP/conda-env-ramp/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/media/joris/DATA/CDS/RAMP/conda-env-ramp/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/joris/DATA/CDS/RAMP/conda-env-ramp/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/media/joris/DATA/CDS/RAMP/conda-env-ramp/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/media/joris/DATA/CDS/RAMP/conda-env-ramp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/media/joris/DATA/CDS/RAMP/conda-env-ramp/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/joris/DATA/CDS/RAMP/conda-env-ramp/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/joris/DATA/CDS/RAMP/conda-env-ramp/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/media/joris/DATA/CDS/RAMP/conda-env-ramp/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/media/joris/DATA/CDS/RAMP/conda-env-ramp/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/joris/DATA/CDS/RAMP/conda-env-ramp/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/joris/DATA/CDS/RAMP/ramp-board/databoard/views.py", line 103, in login
    form.password.data, user.hashed_password):
  File "/media/joris/DATA/CDS/RAMP/ramp-board/databoard/utils.py", line 68, in check_password
    return bcrypt.checkpw(password, hashed_p)
  File "/media/joris/DATA/CDS/RAMP/conda-env-ramp/lib/python3.6/site-packages/bcrypt/__init__.py", line 108, in checkpw
    ret = hashpw(password, hashed_password)
  File "/media/joris/DATA/CDS/RAMP/conda-env-ramp/lib/python3.6/site-packages/bcrypt/__init__.py", line 87, in hashpw
    raise ValueError("Invalid salt")
ValueError: Invalid salt
```

**Comment by glemaitre** [comment]
It was working before the merge of yesterday. Weird.

**Comment by glemaitre** [comment]
Basically I have the same issue in my PR now. I did not have it before.

**Comment by glemaitre** [comment]
cf https://travis-ci.com/paris-saclay-cds/ramp-board/jobs/161419200#L1078
